create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  is_guest boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.cloud_saves (
  profile_id uuid primary key references public.profiles(id) on delete cascade,
  xp integer not null default 0,
  badges text[] not null default '{}',
  active_mission_id text not null default 'royal-island-tour',
  active_vehicle_id text not null default 'krung-compact',
  unlocked_vehicle_ids text[] not null default '{krung-compact}',
  completed_mission_ids text[] not null default '{}',
  discovered_place_ids text[] not null default '{}',
  discovery_daily_xp_by_district jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.leaderboard_runs (
  id bigint generated by default as identity primary key,
  mission_id text not null,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  vehicle_id text not null,
  time_ms integer not null check (time_ms > 0),
  created_at timestamptz not null default now()
);

drop table if exists public.place_cache;

create table if not exists public.curated_places (
  id text primary key,
  summary jsonb not null,
  district_id text not null,
  category text not null,
  is_active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.google_place_index (
  google_place_id text primary key,
  summary jsonb not null,
  district_id text not null,
  category text not null,
  last_seen_at timestamptz not null default now(),
  import_run_id uuid,
  is_active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.google_place_response_cache (
  cache_key text primary key,
  google_place_id text not null references public.google_place_index(google_place_id) on delete cascade,
  language_code text not null check (language_code in ('th', 'en')),
  payload jsonb not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.place_import_runs (
  id uuid primary key default gen_random_uuid(),
  mode text not null,
  status text not null check (status in ('running', 'completed', 'failed')),
  quota_used integer not null default 0,
  request_limit integer not null default 300,
  resume_cursor jsonb,
  errors jsonb not null default '[]'::jsonb,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

create table if not exists public.garage_unlocks (
  profile_id uuid not null references public.profiles(id) on delete cascade,
  vehicle_id text not null,
  unlocked_at timestamptz not null default now(),
  primary key (profile_id, vehicle_id)
);

alter table public.profiles enable row level security;
alter table public.cloud_saves enable row level security;
alter table public.leaderboard_runs enable row level security;
alter table public.curated_places enable row level security;
alter table public.google_place_index enable row level security;
alter table public.google_place_response_cache enable row level security;
alter table public.place_import_runs enable row level security;
alter table public.garage_unlocks enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles for select to authenticated using (auth.uid() = id);

drop policy if exists "profiles_upsert_own" on public.profiles;
create policy "profiles_upsert_own" on public.profiles for insert to authenticated with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "cloud_saves_select_own" on public.cloud_saves;
create policy "cloud_saves_select_own" on public.cloud_saves for select to authenticated using (auth.uid() = profile_id);

drop policy if exists "cloud_saves_insert_own" on public.cloud_saves;
create policy "cloud_saves_insert_own" on public.cloud_saves for insert to authenticated with check (auth.uid() = profile_id);

drop policy if exists "cloud_saves_update_own" on public.cloud_saves;
create policy "cloud_saves_update_own" on public.cloud_saves for update to authenticated using (auth.uid() = profile_id) with check (auth.uid() = profile_id);

drop policy if exists "leaderboard_read_all" on public.leaderboard_runs;
create policy "leaderboard_read_all" on public.leaderboard_runs for select to authenticated using (true);

drop policy if exists "leaderboard_insert_own" on public.leaderboard_runs;
create policy "leaderboard_insert_own" on public.leaderboard_runs for insert to authenticated with check (auth.uid() = profile_id);

drop policy if exists "curated_places_read_all" on public.curated_places;
create policy "curated_places_read_all" on public.curated_places for select to anon, authenticated using (is_active);

drop policy if exists "garage_unlocks_select_own" on public.garage_unlocks;
create policy "garage_unlocks_select_own" on public.garage_unlocks for select to authenticated using (auth.uid() = profile_id);

drop policy if exists "garage_unlocks_insert_own" on public.garage_unlocks;
create policy "garage_unlocks_insert_own" on public.garage_unlocks for insert to authenticated with check (auth.uid() = profile_id);

create index if not exists leaderboard_runs_mission_time_idx on public.leaderboard_runs (mission_id, time_ms);
create index if not exists curated_places_category_district_idx on public.curated_places (category, district_id);
create index if not exists google_place_index_category_district_idx on public.google_place_index (category, district_id);
create index if not exists google_place_index_last_seen_idx on public.google_place_index (last_seen_at);
create index if not exists google_place_response_cache_expiry_idx on public.google_place_response_cache (expires_at);
create index if not exists place_import_runs_started_idx on public.place_import_runs (started_at desc);

grant usage on schema public to anon, authenticated, service_role;
grant select on public.curated_places to anon, authenticated;
revoke all on public.google_place_index from anon, authenticated;
revoke all on public.google_place_response_cache from anon, authenticated;
revoke all on public.place_import_runs from anon, authenticated;
grant select on public.google_place_index to service_role;
grant select, insert, update, delete on public.curated_places to service_role;
grant select, insert, update, delete on public.google_place_index to service_role;
grant select, insert, update, delete on public.google_place_response_cache to service_role;
grant select, insert, update, delete on public.place_import_runs to service_role;
