create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  is_guest boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.cloud_saves (
  profile_id uuid primary key references public.profiles(id) on delete cascade,
  xp integer not null default 0,
  badges text[] not null default '{}',
  active_mission_id text not null default 'royal-island-tour',
  active_vehicle_id text not null default 'krung-compact',
  unlocked_vehicle_ids text[] not null default '{krung-compact}',
  completed_mission_ids text[] not null default '{}',
  discovered_place_ids text[] not null default '{}',
  updated_at timestamptz not null default now()
);

create table if not exists public.leaderboard_runs (
  id bigint generated by default as identity primary key,
  mission_id text not null,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  vehicle_id text not null,
  time_ms integer not null check (time_ms > 0),
  created_at timestamptz not null default now()
);

create table if not exists public.place_cache (
  google_place_id text primary key,
  summary jsonb not null,
  detail jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.garage_unlocks (
  profile_id uuid not null references public.profiles(id) on delete cascade,
  vehicle_id text not null,
  unlocked_at timestamptz not null default now(),
  primary key (profile_id, vehicle_id)
);

alter table public.profiles enable row level security;
alter table public.cloud_saves enable row level security;
alter table public.leaderboard_runs enable row level security;
alter table public.place_cache enable row level security;
alter table public.garage_unlocks enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles for select to authenticated using (auth.uid() = id);

drop policy if exists "profiles_upsert_own" on public.profiles;
create policy "profiles_upsert_own" on public.profiles for insert to authenticated with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "cloud_saves_select_own" on public.cloud_saves;
create policy "cloud_saves_select_own" on public.cloud_saves for select to authenticated using (auth.uid() = profile_id);

drop policy if exists "cloud_saves_insert_own" on public.cloud_saves;
create policy "cloud_saves_insert_own" on public.cloud_saves for insert to authenticated with check (auth.uid() = profile_id);

drop policy if exists "cloud_saves_update_own" on public.cloud_saves;
create policy "cloud_saves_update_own" on public.cloud_saves for update to authenticated using (auth.uid() = profile_id) with check (auth.uid() = profile_id);

drop policy if exists "leaderboard_read_all" on public.leaderboard_runs;
create policy "leaderboard_read_all" on public.leaderboard_runs for select to authenticated using (true);

drop policy if exists "leaderboard_insert_own" on public.leaderboard_runs;
create policy "leaderboard_insert_own" on public.leaderboard_runs for insert to authenticated with check (auth.uid() = profile_id);

drop policy if exists "place_cache_read_all" on public.place_cache;
create policy "place_cache_read_all" on public.place_cache for select to authenticated using (true);

drop policy if exists "garage_unlocks_select_own" on public.garage_unlocks;
create policy "garage_unlocks_select_own" on public.garage_unlocks for select to authenticated using (auth.uid() = profile_id);

drop policy if exists "garage_unlocks_insert_own" on public.garage_unlocks;
create policy "garage_unlocks_insert_own" on public.garage_unlocks for insert to authenticated with check (auth.uid() = profile_id);

create index if not exists leaderboard_runs_mission_time_idx on public.leaderboard_runs (mission_id, time_ms);
create index if not exists place_cache_updated_idx on public.place_cache (updated_at);
